branch-defaults:
  test-branch:
    environment: menufy-test-2
environment-defaults:
  menufy-test-2:
    branch: null
    repository: null
global:
  application_name: menufy_test_2
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.9.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
